#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""阶段 6 B 侧校验：SHA256 + manifest + 只读冻结 + 版本复检 + URL 交叉校验

用法: python scripts/audit/stage6_b_verify.py
"""
import hashlib
import json
import os
import platform
import stat
import subprocess
import sys
import io
from datetime import datetime, timezone

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RAW_DIR = os.path.join(REPO_ROOT, 'data', 'raw')

DATASETS = [
    'longmemeval_cleaned_2025',
    'longmemeval_v2_2026',
    't2ranking_2023',
    'stabletoolbench_2024',
    'multiwoz_2_2_2020',
]

# 下载脚本 URL 列表中预期的文件（用于交叉校验，P1-2 修复）
EXPECTED_FILES = {
    'longmemeval_cleaned_2025': ['longmemeval_oracle.json', 'longmemeval_s_cleaned.json'],
    'longmemeval_v2_2026': ['questions.jsonl', 'trajectories.jsonl', 'SCHEMA.md', 'LICENSE'],
    't2ranking_2023': ['queries.dev.tsv', 'qrels.retrieval.dev.tsv', 'collection.tsv'],
    'stabletoolbench_2024': ['G1_instruction.json'],
    'multiwoz_2_2_2020': ['dialogues_001.json'],
}


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return h.hexdigest()


def check_readonly(path):
    st = os.stat(path)
    return not (st.st_mode & stat.S_IWUSR), oct(st.st_mode & 0o777)


def set_readonly(path):
    """设置文件为只读（P2-2 修复：补全 os.chmod 调用）。

    Windows 下额外通过 attrib +R 设置 DOS 只读属性（P3-1 修复）。
    """
    os.chmod(path, 0o444)
    if platform.system() == 'Windows':
        subprocess.run(['attrib', '+R', path], check=False, capture_output=True)


def main():
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    print(f'========== 阶段 6 B 侧校验 ({now}) ==========')
    print()

    manifest = {
        'generated_at': now,
        'generated_by': 'Annotator B (DGXD01)',
        'datasets': {}
    }

    all_ok = True

    for ds_id in DATASETS:
        subset_dir = os.path.join(RAW_DIR, ds_id, 'v0_subset')
        print(f'--- {ds_id} ---')

        if not os.path.isdir(subset_dir):
            print(f'  ❌ 目录不存在: {subset_dir}')
            manifest['datasets'][ds_id] = {'status': 'dir_not_found'}
            all_ok = False
            continue

        files = sorted([f for f in os.listdir(subset_dir)
                        if f != 'download.log' and not f.startswith('.')])

        if not files:
            print(f'  ❌ 无数据文件（仅 download.log）')
            manifest['datasets'][ds_id] = {'status': 'no_data_files'}
            all_ok = False
            continue

        # P1-2 修复：与下载脚本 URL 列表交叉校验
        expected = EXPECTED_FILES.get(ds_id, [])
        missing = [f for f in expected if f not in files]
        unexpected = [f for f in files if f not in expected]

        ds_manifest = {
            'status': 'ok',
            'expected_files': expected,
            'missing_files': missing,
            'unexpected_files': unexpected,
            'files': []
        }
        for fname in files:
            fpath = os.path.join(subset_dir, fname)
            fsize = os.path.getsize(fpath)
            fhash = sha256_file(fpath)
            ro, mode = check_readonly(fpath)

            # P2-2 修复：若文件可写，自动设为只读
            if not ro:
                set_readonly(fpath)
                ro, mode = check_readonly(fpath)

            entry = {
                'filename': fname,
                'size_bytes': fsize,
                'sha256': fhash,
                'read_only': ro,
                'mode': mode,
            }
            ds_manifest['files'].append(entry)

            ro_mark = '✅' if ro else '⚠️'
            print(f'  {fname}: {fsize} bytes, SHA256={fhash[:16]}..., {ro_mark} readonly={ro}')

        # P1-2 修复：报告缺失/意外文件
        if missing:
            print(f'  ⚠️ 预期但缺失: {missing}')
        if unexpected:
            print(f'  ⚠️ 意外文件（不在脚本 URL 列表）: {unexpected}')

        manifest['datasets'][ds_id] = ds_manifest
        print()

    # 写 manifest
    manifest_path = os.path.join(REPO_ROOT, 'evidence', 'hashes', 'stage6_manifest.json')
    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    print(f'Manifest: {os.path.relpath(manifest_path, REPO_ROOT)}')

    # 写 hash txt
    hash_path = os.path.join(REPO_ROOT, 'evidence', 'hashes', 'stage6_subset_hash.txt')
    with open(hash_path, 'w', encoding='utf-8') as f:
        f.write(f'# Stage 6 B-side verification hashes ({now})\n')
        f.write(f'# Generated by Annotator B (DGXD01)\n\n')
        for ds_id in DATASETS:
            ds = manifest['datasets'].get(ds_id, {})
            if ds.get('status') != 'ok':
                f.write(f'{ds_id}: {ds.get("status", "unknown")}\n\n')
                continue
            f.write(f'[{ds_id}]\n')
            for entry in ds['files']:
                f.write(f'{entry["sha256"]}  {ds_id}/{entry["filename"]}\n')
            f.write('\n')
    print(f'Hash file: {os.path.relpath(hash_path, REPO_ROOT)}')
    print()

    # 只读检查
    readonly_ok = True
    print('--- 只读检查 ---')
    for ds_id in DATASETS:
        ds = manifest['datasets'].get(ds_id, {})
        if ds.get('status') != 'ok':
            continue
        for entry in ds['files']:
            if not entry['read_only']:
                print(f'  ⚠️ {ds_id}/{entry["filename"]} 可写（mode={entry["mode"]}）')
                readonly_ok = False
    if readonly_ok:
        print('  ✅ 全部文件不可写（只读）')
    else:
        print('  ⚠️ 部分文件可写，需设为只读')
    print()

    # 版本复检
    print('--- 版本复检 ---')
    log_path = os.path.join(REPO_ROOT, 'registry', 'dataset_registry.csv')
    import csv
    with open(log_path, 'r', encoding='utf-8-sig') as f:
        registry = {r['dataset_id']: r for r in csv.DictReader(f)}

    for ds_id in DATASETS:
        reg = registry.get(ds_id, {})
        version = reg.get('version', '')
        url = reg.get('data_url', '')
        conclusion = reg.get('conclusion', '')
        ds = manifest['datasets'].get(ds_id, {})
        file_count = len(ds.get('files', []))
        total_size = sum(e['size_bytes'] for e in ds.get('files', []))
        print(f'  {ds_id}: version={version}, files={file_count}, total={total_size} bytes')
        print(f'    conclusion={conclusion[:80]}')
    print()

    # 下载日志交叉验证
    print('--- 下载日志交叉验证 ---')
    for ds_id in DATASETS:
        log_file = os.path.join(RAW_DIR, ds_id, 'v0_subset', 'download.log')
        if not os.path.isfile(log_file):
            print(f'  {ds_id}: 无 download.log')
            continue
        with open(log_file, 'r', encoding='utf-8-sig') as f:
            log_content = f.read()
        ds = manifest['datasets'].get(ds_id, {})
        for entry in ds.get('files', []):
            fname = entry['filename']
            fsize = entry['size_bytes']
            if str(fsize) in log_content:
                print(f'  ✅ {ds_id}/{fname}: 字节数 {fsize} 与 download.log 一致')
            else:
                print(f'  ⚠️ {ds_id}/{fname}: 字节数 {fsize} 在 download.log 中未找到')
    print()

    # P1-2 修复：URL 列表交叉校验汇总
    print('--- URL 列表交叉校验（P1-2） ---')
    cross_ref_ok = True
    for ds_id in DATASETS:
        ds = manifest['datasets'].get(ds_id, {})
        if ds.get('status') != 'ok':
            continue
        missing = ds.get('missing_files', [])
        unexpected = ds.get('unexpected_files', [])
        if missing:
            print(f'  ⚠️ {ds_id}: 预期但缺失 {missing}')
            cross_ref_ok = False
        if unexpected:
            print(f'  ⚠️ {ds_id}: 意外文件 {unexpected}')
            cross_ref_ok = False
        if not missing and not unexpected:
            print(f'  ✅ {ds_id}: 文件列表与脚本 URL 一致')
    print()

    print(f'结论: {"✅ 全部通过" if all_ok and readonly_ok and cross_ref_ok else "⚠️ 存在需关注项"}')


if __name__ == '__main__':
    main()
