# -*- coding: utf-8 -*-
"""Kylin OS Agent Memory data work package - metadata and constants."""

import os

PKG_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

DATE = "2026-08-07"
DOC_VERSION = "v1.0"
MANUAL_FILE = "02_麒麟OS_Agent_记忆模块数据查找选型与质量审计指导手册_v1.0_20260729.docx"

DIRS = [
    "data/raw",
    "data/interim",
    "data/processed",
    "data/gold/dev",
    "data/gold/regression",
    "data/gold/sealed_test",
    "data/runtime_replay",
    "registry",
    "evidence/source",
    "evidence/ai_outputs",
    "evidence/audit",
    "evidence/runtime",
    "evidence/hashes",
    "reports",
    "scripts/download",
    "scripts/validate",
    "scripts/convert",
    "scripts/split",
    "scripts/evaluate",
    "worklog",
]

TASK_CATEGORIES = [
    ("preference", "偏好记忆"),
    ("retrieval", "知识检索"),
    ("conflict", "冲突处理"),
    ("forgetting", "精准遗忘"),
    ("tool_result", "Tool Result"),
    ("end_to_end", "端到端会话"),
]

REQUIREMENT_MAPPING = [
    {
        "requirement": "多源接入（工具执行结果、用户行为、手动配置）",
        "ability": "数据接入与统一解析",
        "dataset": "tool_result / preference",
        "gold": "source_event_id、status、tool、args、result、side_effect",
        "metric": "解析成功率、字段完整率",
        "evidence": "evidence/audit/sample_audit_report.md",
        "build": "自建+真实回放",
    },
    {
        "requirement": "偏好动态捕捉与版本更新",
        "ability": "偏好提取/更新/撤销",
        "dataset": "preference",
        "gold": "preference_type、value、scope、confidence、operation",
        "metric": "Precision / Recall / F1 >= 85%",
        "evidence": "data/gold/dev/*.jsonl",
        "build": "自建为主，LongMemEval 辅助",
    },
    {
        "requirement": "知识结构化整合与关联检索",
        "ability": "知识检索",
        "dataset": "retrieval",
        "gold": "relevant_ids、relevance、hard_negative_ids、expected_answer_points",
        "metric": "Recall@K >= 85%，MRR/nDCG",
        "evidence": "data/gold/dev/retrieval.jsonl",
        "build": "T2Ranking/DuReader 辅助+自建 OS 知识",
    },
    {
        "requirement": "冲突处理",
        "ability": "冲突识别与决策",
        "dataset": "conflict",
        "gold": "conflict_type、candidates、winner、resolution_reason",
        "metric": "决策准确率 >= 88%",
        "evidence": "data/gold/dev/conflict.jsonl",
        "build": "自建为主，MultiWOZ 负样本辅助",
    },
    {
        "requirement": "敏感信息过滤与精准遗忘",
        "ability": "精准遗忘/安全",
        "dataset": "forgetting",
        "gold": "forget_instruction、target_ids、must_keep、checkpoints",
        "metric": "删除正确率、误删率、残留数=0",
        "evidence": "data/gold/dev/forgetting.jsonl",
        "build": "自建为主，LongMemEval abstention 辅助",
    },
    {
        "requirement": "短中长期记忆流转与工具结果沉淀",
        "ability": "Tool Result / 记忆分层",
        "dataset": "tool_result",
        "gold": "status、persist_policy、side_effect、failure_reason",
        "metric": "状态判定正确率，失败/超时覆盖",
        "evidence": "data/gold/dev/tool_result.jsonl",
        "build": "自建+StableToolBench 静态子集辅助",
    },
    {
        "requirement": "端侧延迟与性能",
        "ability": "检索响应时间",
        "dataset": "retrieval + runtime_replay",
        "gold": "fixed corpus + query set",
        "metric": "P50/P95 <= 500ms，冷/热启动",
        "evidence": "evidence/runtime/environment_manifest.md",
        "build": "麒麟虚拟机真实回放",
    },
    {
        "requirement": "跨会话复用、重启恢复与端到端演示",
        "ability": "端到端会话",
        "dataset": "end_to_end",
        "gold": "turns、events、expected_memory、expected_response",
        "metric": "端到端案例通过率",
        "evidence": "data/gold/dev/end_to_end.jsonl",
        "build": "麒麟环境生成+LoCoMo 辅助",
    },
]

CANDIDATES = [
    {
        "dataset_id": "longmemeval_cleaned_2025",
        "formal_name": "LongMemEval (cleaned)",
        "task": "偏好/检索/冲突/遗忘/端到端辅助",
        "publisher": "Di Wu 等（官方仓库 xiaowu0162/LongMemEval）",
        "official_url": "https://github.com/xiaowu0162/LongMemEval",
        "data_url": "https://huggingface.co/datasets/xiaowu0162/longmemeval-cleaned",
        "paper": "https://arxiv.org/abs/2410.10813 (ICLR 2025)",
        "version": "cleaned 2025-09 更新；HF resolve/main；仓库 main 2026-08-07 访问",
        "license": "MIT（仓库 LICENSE 原文已存档）",
        "allowed_uses": "研究、修改、内部演示、公开展示、再分发（以 LICENSE 原文为准）",
        "scale": "500 questions x 5 abilities；oracle/S/M 三档",
        "labels": "question_id/question_type/question/answer/haystack_sessions/answer_session_ids",
        "known_issues": "数据托管于 HuggingFace，大文件下载受网络限制；公开榜单结果不可直接作为本项目成绩",
        "conclusion": "核心候选（待 Reviewer 批准）",
        "download_status": "已下载 longmemeval_oracle.json（手动下载）",
        "score": 88,
    },
    {
        "dataset_id": "longmemeval_v2_2026",
        "formal_name": "LongMemEval-V2",
        "task": "Tool Result/知识检索/端到端辅助",
        "publisher": "Di Wu 等（官方仓库 xiaowu0162/LongMemEval-V2）",
        "official_url": "https://github.com/xiaowu0162/LongMemEval-V2",
        "data_url": "https://huggingface.co/datasets/xiaowu0162/longmemeval-v2",
        "paper": "https://arxiv.org/abs/2605.12493",
        "version": "repo main 2026-08-07 访问；README/LICENSE 已存档",
        "license": "Apache-2.0（仓库 LICENSE 原文已存档）",
        "allowed_uses": "研究、修改、内部演示、公开展示、再分发（以 LICENSE 原文为准）",
        "scale": "451 questions；最多 500 trajectories；最大 115M tokens",
        "labels": "question、trajectory history、evidence、answer、latency",
        "known_issues": "数据量极大，需抽取固定小规模子集；web/enterprise 域需按任务拆分",
        "conclusion": "核心候选（补充）",
        "download_status": "已下载 questions.jsonl + SCHEMA/checksums（手动下载）",
        "score": 84,
    },
    {
        "dataset_id": "locomo_2024",
        "formal_name": "LoCoMo",
        "task": "端到端/长期会话辅助",
        "publisher": "SNAP Research (Stanford)",
        "official_url": "https://github.com/snap-research/locom",
        "data_url": "",
        "paper": "论文标题：LoCoMo: Evaluating Very Long-Term Conversational Memory of LLM Agents（arXiv 链接待人工确认）",
        "version": "官方仓库 snap-research/locom 已核实；README 数据入口待网络恢复后确认",
        "license": "待核验",
        "allowed_uses": "待人工/法务确认",
        "scale": "10 个长期会话场景；QA/幻觉/遗忘多任务",
        "labels": "conversation、question、answer、evidence",
        "known_issues": "官方数据经 Google Drive 分发，体积大且不稳定；仓库未声明明确 License（API 显示 NOASSERTION），使用前需人工/法务确认",
        "conclusion": "补充候选（待核验）",
        "download_status": "网络受限，未下载",
        "score": 72,
    },
    {
        "dataset_id": "stabletoolbench_2024",
        "formal_name": "StableToolBench",
        "task": "Tool Result",
        "publisher": "THUNLP-MT（清华）",
        "official_url": "https://github.com/THUNLP-MT/StableToolBench",
        "data_url": "https://github.com/THUNLP-MT/StableToolBench",
        "paper": "arXiv:2403.07714（待人工确认）",
        "version": "master 仓库 zip 已下载（含 data_example 官方样例）",
        "license": "Apache-2.0（仓库 LICENSE 原文已存档）",
        "allowed_uses": "研究、修改、内部演示、公开展示、再分发（以 LICENSE 原文为准）",
        "scale": "静态工具调用子集；data_example 提供样例结构",
        "labels": "tool call、state、pass_rate/preference 结果",
        "known_issues": "需改造成本项目 Tool Result 状态与持久化标签；原始数据未下载",
        "conclusion": "核心候选（补充）",
        "download_status": "已下载官方 data_example 样例（5 个文件）",
        "score": 80,
    },
    {
        "dataset_id": "toolbench_2024",
        "formal_name": "ToolBench",
        "task": "Tool Result 辅助",
        "publisher": "OpenBMB",
        "official_url": "https://github.com/OpenBMB/ToolBench",
        "data_url": "",
        "paper": "arXiv:2402.01030（待人工确认）",
        "version": "master README 已存档",
        "license": "Apache-2.0（官方 README 声明）",
        "allowed_uses": "研究、修改、内部演示、公开展示、再分发（以 LICENSE 原文为准）",
        "scale": "单工具/多工具/工具规划多级；数据体量大",
        "labels": "instructions、answer、tool calls",
        "known_issues": "数据过大，依赖动态 API；只宜抽取静态缓存子集",
        "conclusion": "补充候选（不进入首版封存）",
        "download_status": "官方说明已存档（Apache-2.0）；data.zip 需手动/大文件下载",
        "score": 68,
    },
    {
        "dataset_id": "t2ranking_2023",
        "formal_name": "T2Ranking",
        "task": "知识检索（中文）",
        "publisher": "THUIR（清华）",
        "official_url": "https://github.com/THUIR/T2Ranking",
        "data_url": "https://huggingface.co/datasets/THUIR/T2Ranking",
        "paper": "https://arxiv.org/abs/2304.03679",
        "version": "dev 2023；queries.dev.tsv + qrels.retrieval.dev.tsv 已下载",
        "license": "待核验（HF Data Card 未下载）",
        "allowed_uses": "待人工/法务确认",
        "scale": "300K+ queries；2.3M passages；TREC qrels 格式",
        "labels": "qid/query/pid/passage/qrels relevance 4 级",
        "known_issues": "Web 检索域与 OS 记忆域有差距；全量过大，只取固定小规模子集",
        "conclusion": "核心候选（中文检索）",
        "download_status": "已下载 dev queries+qrels（官方 HF 镜像）",
        "score": 82,
    },
    {
        "dataset_id": "dureader_retrieval_2022",
        "formal_name": "DuReader Retrieval",
        "task": "知识检索（中文）",
        "publisher": "Baidu",
        "official_url": "https://github.com/baidu/DuReader/tree/master/DuReader-Retrieval",
        "data_url": "https://github.com/PaddlePaddle/RocketQA/tree/main/research/DuReader-Retrieval-Baseline",
        "paper": "https://arxiv.org/abs/2203.10232",
        "version": "README 已存档；数据发布 2022-03",
        "license": "待核验",
        "allowed_uses": "待人工/法务确认",
        "scale": "90K+ queries；8M+ passages",
        "labels": "query/passage/relevance qrels",
        "known_issues": "数据下载需通过官方渠道/千言；Web 检索域与 OS 记忆域有差距",
        "conclusion": "核心候选（二选一）",
        "download_status": "官方说明已存档；数据需在千言/百度渠道注册下载",
        "score": 80,
    },
    {
        "dataset_id": "multiwoz_2_2_2020",
        "formal_name": "MultiWOZ 2.2",
        "task": "冲突/任务对话辅助负样本",
        "publisher": "Google 修正版（budzianowski/multiwoz 仓库托管）",
        "official_url": "https://github.com/budzianowski/multiwoz/tree/master/data/MultiWOZ_2.2",
        "data_url": "https://github.com/budzianowski/multiwoz",
        "paper": "https://arxiv.org/abs/2007.12720",
        "version": "2.2 dev 子集；dialogues_001.json（11.7MB）已下载；仓库 LICENSE/README/schema 已存档",
        "license": "MIT（仓库 LICENSE 原文已存档）",
        "allowed_uses": "研究、修改、内部演示、公开展示、再分发（以 LICENSE 原文为准）",
        "scale": "10K dialogues；belief state 全标注",
        "labels": "goal、turns、belief_state、dialogue acts",
        "known_issues": "不是长期记忆集，不能直接评偏好版本和遗忘；仅作辅助/负样本",
        "conclusion": "补充候选（辅助/负样本）",
        "download_status": "已下载 dev 样本 dialogues_001.json（100 条抽样审计）",
        "score": 74,
    },
    {
        "dataset_id": "dailydialog_2017",
        "formal_name": "DailyDialog",
        "task": "自然表达/闲聊负样本辅助",
        "publisher": "Yanran Li 等",
        "official_url": "http://yanran.li/dailydialog/",
        "data_url": "http://yanran.li/files/ijcnlp_dailydialog.zip",
        "paper": "ACL-IJCNLP 2017（待人工确认链接）",
        "version": "官方页 200 已访问；下载包被本机安全软件拦截",
        "license": "站点条款待核验",
        "allowed_uses": "待人工/法务确认",
        "scale": "13K dialogues；7 种 emotion；CC 类条款待确认",
        "labels": "dialogue、emotion、act",
        "known_issues": "下载文件被 Windows Defender 标记拦截，禁止直接使用；需人工核验官方渠道后重下",
        "conclusion": "仅补充候选（下载阻塞）",
        "download_status": "安全软件拦截，未使用",
        "score": 62,
    },
    {
        "dataset_id": "personachat_2018",
        "formal_name": "PersonaChat (ParlAI)",
        "task": "偏好辅助",
        "publisher": "Facebook AI Research",
        "official_url": "https://github.com/facebookresearch/ParlAI",
        "data_url": "",
        "paper": "arXiv:1801.07243（待人工确认）",
        "version": "待核验",
        "license": "待核验",
        "allowed_uses": "待人工/法务确认",
        "scale": "多轮 persona 对话",
        "labels": "persona、utterance",
        "known_issues": "静态 persona/日常对话不等于动态偏好；ParlAI 页面已归档",
        "conclusion": "补充候选（不进入首版封存）",
        "download_status": "网络受限，未下载",
        "score": 66,
    },
    {
        "dataset_id": "msmarco_2021",
        "formal_name": "MS MARCO",
        "task": "检索辅助",
        "publisher": "Microsoft",
        "official_url": "https://microsoft.github.io/msmarco/",
        "data_url": "",
        "paper": "待核验",
        "version": "官网访问失败（连接被重置），待人工核验",
        "license": "Microsoft Research License/Notice 待核验",
        "allowed_uses": "待人工/法务确认",
        "scale": "百万级 query/passage",
        "labels": "query、passage、qrels",
        "known_issues": "再分发需单独核验 Terms；不进入首版封存",
        "conclusion": "方法论参考（不采用）",
        "download_status": "网络受限，未下载",
        "score": 64,
    },
    {
        "dataset_id": "trec_tracks_2024",
        "formal_name": "TREC (NIST)",
        "task": "检索方法论参考",
        "publisher": "NIST",
        "official_url": "https://trec.nist.gov/",
        "data_url": "",
        "paper": "",
        "version": "官方门户 200 已访问",
        "license": "NIST 官方条款待核验",
        "allowed_uses": "待人工/法务确认",
        "scale": "多个 Track/子集",
        "labels": "topic、qrels",
        "known_issues": "必须明确具体 Track/版本；是评测方法参考而非单一数据集",
        "conclusion": "方法论参考",
        "download_status": "未下载",
        "score": 60,
    },
    {
        "dataset_id": "bpmn_2_0_2013",
        "formal_name": "BPMN 2.0 (OMG 标准)",
        "task": "工作流知识结构参考",
        "publisher": "Object Management Group",
        "official_url": "https://www.omg.org/spec/BPMN/",
        "data_url": "",
        "paper": "",
        "version": "BPMN 2.0 官方规范 PDF 已下载",
        "license": "OMG 标准使用条款",
        "allowed_uses": "作为结构参考；不直接打包发布",
        "scale": "标准文档（非数据集）",
        "labels": "",
        "known_issues": "BPMN 是标准，不是可直接写入评测的单一数据集",
        "conclusion": "结构参考",
        "download_status": "已下载官方规范 PDF（结构参考）",
        "score": 58,
    },
]

SCORE_WEIGHTS = [
    ("赛题能力匹配度", 20),
    ("标签质量", 15),
    ("中文/OS 场景匹配", 12),
    ("来源可信度", 10),
    ("License 与合规", 10),
    ("可复现性", 10),
    ("覆盖度与难度", 8),
    ("数据干净程度", 5),
    ("泄漏风险", 5),
    ("端侧成本", 5),
]

GATES = [
    ("Gate 0", "目录可用，负责人明确，原始数据目录只读/不直接修改", "已完成"),
    ("Gate 1", "每个比赛要求至少对应一个数据子集和一个可计算指标", "已完成（requirement_data_mapping_v1.md）"),
    ("Gate 2", "所有候选有正式名称、版本线索、官方来源和任务说明", "已完成（13 个候选登记；locomo/msmarco 部分待人工复核）"),
    ("Gate 3", "Reviewer 明确标记允许试用/需确认/淘汰", "AI 草稿完成，待 Reviewer 批准"),
    ("Gate 4", "样本可解析，标签定义可理解，人工抽检通过，未命中否决项", "自建候选样本审计通过；公开样本下载受网络阻塞，待执行"),
    ("Gate 5", "核心候选>=80分；补充候选>=65分；批准人签字/记录", "评分草稿完成，待 Reviewer 批准"),
    ("Gate 6", "再次下载可得到同一版本；文件数量和哈希完整", "已生成下载/校验脚本；公开原始包待下载后补哈希"),
    ("Gate 7", "每条 processed 样本可追溯到 raw_id；转换过程无静默丢失", "已完成（转换脚本+测试）"),
    ("Gate 8", "一致性达到团队设定阈值，分歧有裁决，所有标签有 evidence", "候选草稿具备 evidence；双人标注/裁决待人工执行"),
    ("Gate 9", "无用户/会话/模板泄漏；封存集哈希固定；Reviewer 批准", "自建候选已切分+泄漏扫描；封存批准待人工"),
    ("Gate 10", "命令、环境、原始日志、失败样本和统计脚本齐全", "回放准备包已生成；麒麟虚拟机真实执行待人工"),
    ("Gate 11", "另一名同事可从文档复现；报告数字均能回到原始文件", "复现文档已生成；最终数字待回放后回填"),
]

RAW_DATASET_IDS = [
    c["dataset_id"] for c in CANDIDATES if c["download_status"] not in ("未下载", "网络受限，未下载", "安全软件拦截，未使用")
]
